<?php

return [
    'default_disk' => env('UPLOAD_DISK', 'uploads_private'),
    'public_disk' => env('UPLOAD_PUBLIC_DISK', 'uploads_public'),
    'private_disk' => env('UPLOAD_PRIVATE_DISK', 'uploads_private'),
    'default_visibility' => env('UPLOAD_DEFAULT_VISIBILITY', 'private'),
    'default_naming_strategy' => env('UPLOAD_NAMING_STRATEGY', 'system'),
    'default_path_strategy' => env('UPLOAD_PATH_STRATEGY', 'category_date'),
    'max_files_per_request' => (int) env('UPLOAD_MAX_FILES_PER_REQUEST', 10),
    'temporary_upload_ttl_minutes' => (int) env('UPLOAD_TEMP_TTL_MINUTES', 120),
    'categories' => [
        'image' => [
            'enabled' => env('UPLOAD_IMAGE_ENABLED', true),
            'label' => 'Images',
            'extensions' => ['jpg', 'jpeg', 'png', 'webp'],
            'mimes' => ['image/jpeg', 'image/png', 'image/webp'],
            'max_size_kb' => (int) env('UPLOAD_IMAGE_MAX_SIZE_KB', 1024),
            'visibility' => env('UPLOAD_IMAGE_VISIBILITY', 'private'),
            'naming_strategy' => env('UPLOAD_IMAGE_NAMING_STRATEGY', env('UPLOAD_NAMING_STRATEGY', 'system')),
            'optimize' => env('UPLOAD_IMAGE_OPTIMIZE', true),
            'image' => [
                'max_width' => (int) env('UPLOAD_IMAGE_MAX_WIDTH', 1920),
                'max_height' => (int) env('UPLOAD_IMAGE_MAX_HEIGHT', 1920),
                'jpeg_quality' => (int) env('UPLOAD_IMAGE_JPEG_QUALITY', 82),
                'webp_quality' => (int) env('UPLOAD_IMAGE_WEBP_QUALITY', 82),
                'png_compression' => (int) env('UPLOAD_IMAGE_PNG_COMPRESSION', 7),
            ],
        ],
        'document' => [
            'enabled' => env('UPLOAD_DOCUMENT_ENABLED', true),
            'label' => 'Documents',
            'extensions' => ['pdf', 'doc', 'docx', 'txt'],
            'mimes' => [
                'application/pdf',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'text/plain',
            ],
            'max_size_kb' => (int) env('UPLOAD_DOCUMENT_MAX_SIZE_KB', 1024),
            'visibility' => env('UPLOAD_DOCUMENT_VISIBILITY', 'private'),
            'naming_strategy' => env('UPLOAD_DOCUMENT_NAMING_STRATEGY', env('UPLOAD_NAMING_STRATEGY', 'system')),
            'optimize' => env('UPLOAD_DOCUMENT_OPTIMIZE', false),
        ],
        'spreadsheet' => [
            'enabled' => env('UPLOAD_SPREADSHEET_ENABLED', true),
            'label' => 'Spreadsheets',
            'extensions' => ['xls', 'xlsx', 'csv'],
            'mimes' => [
                'application/vnd.ms-excel',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'text/csv',
                'text/plain',
            ],
            'max_size_kb' => (int) env('UPLOAD_SPREADSHEET_MAX_SIZE_KB', 1024),
            'visibility' => env('UPLOAD_SPREADSHEET_VISIBILITY', 'private'),
            'naming_strategy' => env('UPLOAD_SPREADSHEET_NAMING_STRATEGY', env('UPLOAD_NAMING_STRATEGY', 'system')),
            'optimize' => false,
        ],
        'archive' => [
            'enabled' => env('UPLOAD_ARCHIVE_ENABLED', false),
            'label' => 'Archives',
            'extensions' => ['zip'],
            'mimes' => ['application/zip', 'application/x-zip-compressed'],
            'max_size_kb' => (int) env('UPLOAD_ARCHIVE_MAX_SIZE_KB', 1024),
            'visibility' => env('UPLOAD_ARCHIVE_VISIBILITY', 'private'),
            'naming_strategy' => env('UPLOAD_ARCHIVE_NAMING_STRATEGY', env('UPLOAD_NAMING_STRATEGY', 'system')),
            'optimize' => false,
        ],
    ],
];
